name: Build image with rstudio-server stable release 2024.09.1+394 for non-root users and push to dockerhub

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build image with rstudio-server stable release 2024.09.1\+394 and push to dockerhub]
    types:
      - completed

jobs:
  build-from-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to doker hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build rstudio-server docker image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:singularity"
          push: true
          labels: |
            rstudio-server.target-platform=jammy-amd64
            rstudio-server.channel=release
            rstudio-server.version=2024.09.1+394
          tags: |
            ${{secrets.DOCKERHUB_USER}}/rstudio-server:latest-release-singularity
            ${{secrets.DOCKERHUB_USER}}/rstudio-server:2024-09-1-394-singularity
